---
- name: Setup NAS with redundancy
  hosts: samba

  roles:
    - role: samba
      tags: [ network ]

    - role: redundancy
      tags: [ network ]

    - role: mediaserver
      tags: [ media ]
