---
- name: Include config vars
  include_vars: config.yml
  
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install COPS dependencies
  apt:
    pkg:
      - php7.3
      - php7.3-fpm
      - php7.3-gd
      - php7.3-sqlite3 
      - php7.3-json 
      - php7.3-intl 
      - php7.3-xml 
      - php7.3-mbstring
      - php7.3-zip
      - nginx

- name: Reload nginx
  shell: /etc/init.d/nginx reload

- name: Create webapp folder
  file:
    path: "{{ cops_install_dir }}"
    owner: root
    group: root
    state: directory

- name: Clone COPS repository
  git:
    repo: https://github.com/seblucas/cops.git
    dest: "{{ cops_install_dir }}"

- name: Check if composer if installed globally
  stat:
    path: /usr/local/bin/composer
  register: composer

- name: Install composer
  shell: |
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer
  when: not composer.stat.exists

- name: Install global php dependencies
  composer:
    command: require
    global_command: yes
    arguments: fxp/composer-asset-plugin:~1.1

- name: Install COPS PHP dependencies
  composer:
    command: install
    working_dir: "{{ cops_install_dir }}"
    no_dev: yes
    optimize_autoloader: true
