---
- name: Include samba server config
  include_vars: samba_vars.yml
  
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install the Samba and additional packages
  apt:
    name: "{{ samba_packages  }}"
    state: latest
    update_cache: yes

- name: Copy the Customize smb.conf file
  template: 
    src: etc_samba_smb.conf.j2
    dest: /etc/samba/smb.conf
    backup: yes
  notify:
    - Restart Samba

- name: Create Samba users restricted group
  group:
    name: "{{ samba_group_name }}"
    state: present

- name: Add the User(s) to Samba group
  user:
    name: "{{ item.name }}" 
    groups: "{{ samba_group_name }}" 
    append: yes
  with_items: "{{ samba_users }}"

- name: Create Samba Password for User(s)
  shell: "(echo {{ item.smbpasswd }}; echo {{ item.smbpasswd }}) | smbpasswd -s -a {{ item.name }}"
  with_items: "{{ samba_users }}"
