---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install apt HTTPS transport package
  apt:
    name: apt-transport-https
    state: latest

- name: Add Plex.TV apt key
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key 
    state: present

- name: Add Plex repository to sources
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present

- name: Install Plex Media Server
  apt:
    name: plexmediaserver
    state: latest
    update_cache: yes

